Repository kaushikd207/StockSite, pull requests merged in 2021-10, with the labels that each got.

#2 adde html
  index.html
Labels: hactoberfest2021, hactoberfest-accepted

#3 changed
  index.html
Labels: hactoberfest2021, hactoberfest-accepted

#4 Update index.html
  index.html
Labels: hactoberfest2021, hactoberfest-accepted, hactoberfest

#5 Create README.md
  README.md
Labels: hactoberfest2021, hactoberfest-accepted, hactoberfest

#6 Update index.html
  index.html
Labels: hactoberfest-accepted

#7 Update index.html
  index.html
Labels: hactoberfest-accepted

#8 Update index.html
  index.html
Labels: hacktoberfest-accepted

#9 Update index.html
  index.html
Labels: hacktoberfest-accepted

#10 Update index.html
  index.html
Labels: hacktoberfest-accepted

#11 Update index.html
  index.html
Labels: hactoberfest-accepted

#12 Update index.html
  index.html
Labels: hacktoberfest-accepted

#13 Update index.html
  index.html
Labels: hacktoberfest-accepted

#14 body
  index.html
Labels: hacktoberfest-accepted
